name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Create and activate virtual environment
      run: |
        pip install pipenv

    - name: Install dependencies
      run: |
        pipenv install -r requirements.txt

    - name: Add environment variables to Zappa config
      uses: jossef/action-set-json-field@v2.1
      with:
        file: ./zappa_settings.json
        field: prod.environment_variables.RAPID_API_KEY
        value: ${{ secrets.RAPID_API_KEY }}

    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
      run: |
        pipenv run zappa update prod
